language: node_js

node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"

before_install:
  - npm install -g bower
  - bower install

script:
  - gulp ci

cache:
  directories:
    - node_modules
