language: node_js

node_js:
  - "7"
  - "6"
  - "4"

script:
  - gulp ci
  - gulp zip

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key:
    secure: RUN7W3/VCwuHZmqBg8QXbDjhk5dwNMlLqGGJr2MNbVJemt1WlyQeFytpLdm5uGIRxZ569u7rxxvv5FAu7nSq+W2X3ygyw5fL19uR3tZQezIpEEHie4AaAY8Ujp1GzEbF7mF6+vjtA2fBQgYMB7WLWr2PLPgVqRcdNEWztWpcZzsukKOLMa/PgEzu+nbvtXpSycEKlom2iDFm7usBwneu08KD5kNefOu0xW8sPHUxBe5oRgJirPtLwfvvWJiZ1woyUQATfuEvoHDtft2ajU6rrJhZ1L0Y5yzfQgEClTQu7FPhetOo8WctJLX3jpkGF7/iVpPHQRV/QyJKNksBxCiAqHQDRH9WJQyU6/EzjqT5cj0oR5WnqrYi4IP8+DMU7XrzAHbvKh3dyjknVlYOfZtO/bLAyitA2eJEbmHwKttVV1tpU80C/E3uILYdOk2v7XOsbtYSMqLSKKwWXRmgGMYJcqGlkCNz4QAN/jpPb11w+CAUEFrTnqXjbEZ0ry4P2jYrXkruleDpcibncdm2XlvmVp/warvhBXvdPNTd2U8TJ29KO0QiV+VlyqSGqZ4gO1aEg2Hs2pzFdJBrcMjwjhzcS29JkjNHmGDWO0t4apQ3zdpxZOlAjUVEdueUGdJ3lhkwZ0JbTpbywLHfVGlBWc2m1nNVa4wYTdklgc1B+B5Kh58=
  skip_cleanup: true
  file: firebase-sensor.zip
  on:
    tags: true
    repo: seblucas/firebase-sensor
    node: '6'
